import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#757d73",
        "primary": "#006e2b",
        "inverse-on-surface": "#9b9e98",
        "surface-container-highest": "#dde5d9",
        "surface": "#f8faf3",
        "inverse-primary": "#5efd83",
        "secondary-fixed-dim": "#afd9ff",
        "on-error": "#fff7f6",
        "on-surface-variant": "#596158",
        "on-tertiary": "#fff8ef",
        "secondary-dim": "#1c577e",
        "tertiary-fixed-dim": "#eec859",
        "surface-container-high": "#e4eadf",
        "error-container": "#fd795a",
        "surface-variant": "#dde5d9",
        "primary-fixed": "#5efd83",
        "primary-container": "#5efd83",
        "error": "#a73b21",
        "surface-bright": "#f8faf3",
        "tertiary-dim": "#675000",
        "on-secondary": "#f6f9ff",
        "surface-dim": "#d4dcd0",
        "outline-variant": "#acb4a9",
        "on-primary-fixed-variant": "#006829",
        "on-secondary-container": "#1a567d",
        "secondary": "#2c648b",
        "background": "#f8faf3",
        "surface-tint": "#006e2b",
        "tertiary": "#755c00",
        "on-secondary-fixed": "#004367",
        "error-dim": "#791903",
        "on-surface": "#2d342c",
        "secondary-container": "#cce5ff",
        "secondary-fixed": "#cce5ff",
        "primary-fixed-dim": "#4dee76",
        "on-tertiary-fixed": "#483800",
        "on-tertiary-container": "#5f4a00",
        "on-secondary-fixed-variant": "#276087",
        "on-primary": "#e9ffe5",
        "on-error-container": "#6e1400",
        "on-primary-fixed": "#00481a",
        "tertiary-fixed": "#fdd665",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#0c0f0b",
        "surface-container-low": "#f1f5ec",
        "tertiary-container": "#fdd665",
        "on-tertiary-fixed-variant": "#6a5300",
        "on-primary-container": "#005d23",
        "surface-container": "#eaf0e6",
        "primary-dim": "#006125",
        "on-background": "#2d342c"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
      }
    },
  },
  plugins: [],
};
export default config;
